---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: restart telegraf on host
  ansible.builtin.systemd:
    name: "telegraf"
    state: restarted
    enabled: yes
    daemon_reload: yes
