---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: restart wireguard
  ansible.builtin.systemd:
    name: "wg-quick@{{ wireguard_interface_name }}"
    state: restarted
    enabled: yes
