---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: restart ssl-router
  ansible.builtin.systemd:
    name: "{{ _ssl_router_systemd_unit_name }}"
    enabled: true
    daemon_reload: true
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
