FROM {{ item.image }}
RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        systemd systemd-sysv python3 ca-certificates curl fuse-overlayfs nftables crun && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /etc/containers && \
    printf '%s\n' '[engine]' 'runtime = "runc"' > /etc/containers/containers.conf && \
    systemctl mask getty@tty1.service && \
    echo "root:100000:65536" > /etc/subuid && \
    echo "root:100000:65536" > /etc/subgid
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
