
- name: iptables | Check docker systemd unit file exists
  ansible.builtin.stat:
    path: "/lib/systemd/system/docker.service"
  register: _iptables_docker_systemd_file_stat

- name: iptables | Restart docker service
  ansible.builtin.systemd:
    name: "docker"
    state: restarted
  when: "{{ _iptables_docker_systemd_file_stat.stat.exists }}"
