---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: restart cf_ddns
  ansible.builtin.systemd:
    name: "{{ _cf_ddns_systemd_unit_name }}"
    enabled: yes
    daemon_reload: yes
    state: restarted
