---
- name: Prepare (podman)
  hosts: all
  gather_facts: false
  vars_files:
    - ../shared/vars/common.yml
  tasks:
    - name: Import shared prepare tasks
      ansible.builtin.import_tasks: ../shared/tasks/prepare.yml
