---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: restart ssh
  ansible.builtin.systemd:
    name: "ssh"
    state: restarted
    enabled: yes

- name: update grub
  ansible.builtin.shell:
    cmd: "update-grub"
  changed_when: False

- name: restart systemd-journald
  ansible.builtin.systemd:
    name: "systemd-journald.service"
    state: restarted
    enabled: yes

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: "systemd-resolved.service"
    state: restarted
    enabled: yes
  ignore_errors: "{{ not _init_systemd_resolved_unit_register.stat.exists }}"

- name: restart sysfsutils
  ansible.builtin.systemd:
    name: "sysfsutils.service"
    state: restarted
    enabled: yes
  ignore_errors: "{{ not _init_kernel_sysfsutils_register.stat.exists }}"

- name: restart systemd-timesyncd
  ansible.builtin.systemd:
    name: "systemd-timesyncd.service"
    state: restarted
    enabled: yes
  ignore_errors: "{{ not _init_time_timesyncd_unit_register.stat.exists }}"
