---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

iptables_inf_ext: "{{ ansible_default_ipv4.interface }}"

iptables_ports:
  - port: 22
    protocol: tcp
#  - port: 80
#    protocol: tcp
#    src_v4: 0.0.0.0/0
#    src_v6: ::/0
#    skip_v6: false 
iptables_forwarded_ports: []
#  - forwarded_inf: eth0
#    forwarded_port: 22
#    protocol: tcp
#    dst_port: 22
#    dst_address: 192.168.1.1
iptables_docker_ports: []
#  - port: 80
#    protocol: tcp
#    src_v4: 0.0.0.0/0

iptables_randomized_ext_ips: []
# minutes
iptables_randomized_ext_ips_timer: 5

iptables_external_ping_enable: false
# per minute
iptables_external_ping_limit: 10
# block outgoing connections to local addresses
iptables_disable_local_output: false
iptables_disable_local_excluded_ipv4_ranges: []
iptables_disable_local_excluded_ipv6_ranges: []
# for k8s nodes
iptables_ipv4_forward_enable: false
iptables_ext_inf_masquerade: false
