---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

ssl_router_base_dir: "/opt/ssl-router"
ssl_router_image_name: "nginx"
ssl_router_image_version: "stable-alpine"
ssl_router_https_port: 443
ssl_router_upstream_map: {}
#  k8s:
#    regex: ".*abc.com"
#    host: abc.abc
#    port: "5443"
