---

- block:

    - name: cf_ddns | install packages
      ansible.builtin.apt:
        name:
          - "podman"
          - "uidmap"
          - "slirp4netns"
        update_cache: yes
        install_recommends: no
    
    - name: cf_ddns | start the Podman container
      containers.podman.podman_container:
        name: "{{ _cf_ddns_container_name }}"
        image: "{{ cf_ddns_image_name }}:{{ cf_ddns_image_version }}"
        state: started
        restart_policy: always
        pull: "always"
        env:
          CF_DDNS_TOKEN: "{{ cf_ddns_token }}"
          CF_DDNS_ZONE_ID: "{{ cf_ddns_zone_id }}"
          CF_DDNS_HOST: "{{ cf_ddns_host }}"
          CF_DDNS_INTERVAL: "{{ cf_ddns_interval }}"
          CF_DDNS_TTL: "{{ cf_ddns_ttl }}"
          CF_DDNS_PROXIED: "{{ cf_ddns_proxied }}"
          CF_DDNS_LOGLEVEL: "{{ cf_ddns_loglevel }}"
          CF_DDNS_METRICS_PORT: "{{ cf_ddns_metrics_port }}"
    
    - name: cf_ddns | generate systemd unit file for the container
      ansible.builtin.command: podman generate systemd --name "{{ _cf_ddns_container_name }}" --new
      register: _cf_ddns_systemd_unit_register
      check_mode: false
      changed_when: false
    
    - name: cf_ddns | fix the generated systemd unit file content
      ansible.builtin.set_fact:
        _systemd_unit_file_content: "{{ _cf_ddns_systemd_unit_register.stdout | regex_replace('--rm\\s+', '') }}"

    - name: cf_ddns | save the generated systemd unit file
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ _cf_ddns_systemd_unit_name }}"
        content: "{{ _systemd_unit_file_content }}"
        owner: root
        group: root
        mode: '0600'
      notify: restart cf_ddns
      
    - name: cf_ddns | flush handlers before service start
      ansible.builtin.meta: flush_handlers
    
    - name: cf_ddns | enable and start the systemd unit file for the container
      ansible.builtin.systemd:
        name: "{{ _cf_ddns_systemd_unit_name }}"
        enabled: yes
        state: started
        daemon_reload: yes

  tags: ["cf_ddns", "cf-ddns"]