---
# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- block:
    - name: cf_ddns | install packages
      ansible.builtin.apt:
        name:
          - podman
          - runc
          - uidmap
          - slirp4netns
        update_cache: yes
        install_recommends: no

    - name: cf_ddns | copy systemd unit file
      ansible.builtin.template:
        src: .service.j2
        dest: "/etc/systemd/system/{{ _cf_ddns_systemd_unit_name }}"
        owner: root
        group: root
        mode: "0600"
      notify: restart cf_ddns

    # to avoid 2 restarts during the first deploy
    - name: cf_ddns | flush handlers
      ansible.builtin.meta: flush_handlers

    - name: cf_ddns| start service
      ansible.builtin.systemd:
        name: "{{ _cf_ddns_systemd_unit_name }}"
        state: started
        enabled: yes
        daemon_reload: yes
      ignore_errors: "{{ ansible_check_mode }}"

  tags: ["cf_ddns", "cf-ddns"]
