---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

scw_k8s_kosmos_agent_binary_url: "https://github.com/scaleway/k8s-agent/releases/latest/download/k8s-agent_linux_amd64"

scw_k8s_kosmos_agent_pool_region: ""
scw_k8s_kosmos_agent_pool_id: ""
scw_k8s_kosmos_agent_secret_key: ""
