---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- block:

  - name: Install docker-compose
    ansible.builtin.apt:
      name: "{{ packages }}"
      install_recommends: no
      update_cache: no
    vars:
      packages:
        - docker-compose

  tags: ["docker"]
