---

- block:

  - name: Install docker python modules {{ packages }}
    ansible.builtin.pip:
      name: "{{ packages }}"
    vars:
      packages:
        - "docker-compose=={{ docker_compose_version }}"
        - "docker=={{ docker_docker_pip_version }}"

  tags: ["docker"]
