---

# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- block:

  - name: install/upgrade Docker
    ansible.builtin.import_tasks: install-docker.yml

  - name: install/upgrade Docker Compose
    ansible.builtin.import_tasks: install-compose.yml

  - name: Schedule a cleanup (every day)
    ansible.builtin.cron:
      name: Docker cleanup
      special_time: daily
      job: "docker system prune --force"
      state: "{{ docker_schedule_cleanup_state }}"

  tags: ["docker"]
