---

- block:

  - name: hosts | set hostname
    ansible.builtin.hostname:
      name: "{{ init_hostname }}"
      use: systemd

  # some cloud scripts change the hosts file. We have changes every run because of it
  - name: hosts | remove immutable flag from /etc/hosts
    ansible.builtin.file:
      path: /etc/hosts
      attributes: '-i'
    changed_when: false
    when: init_block_hosts_file | bool

  - name: hosts | copy hosts file
    ansible.builtin.template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'

  - name: hosts | set immutable flag for /etc/hosts
    ansible.builtin.file:
      path: /etc/hosts
      attributes: '+i'
    changed_when: false
    when: init_block_hosts_file | bool

  tags: ['init', 'init-hosts']
