---
# Copyright © 2025 kogeler
# SPDX-License-Identifier: Apache-2.0

- name: ssl-router | tasks
  tags: ["ssl-router", "ssl_router"]
  block:

    - name: ssl-route | install packages
      ansible.builtin.apt:
        name:
          - "podman"
          - "runc"
          - "uidmap"
          - "slirp4netns"
        update_cache: true
        install_recommends: false

    - name: ssl-route | create directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode | default('0755') }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
      loop:
        - { path: "{{ ssl_router_base_dir }}" }

    - name: ssl-route | copy templates
      ansible.builtin.template:
        src: "{{ item.dst }}.j2"
        dest: "{{ ssl_router_base_dir }}/{{ item.dst_path }}/{{ item.dst }}"
        mode: "{{ item.mode | default('600') }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
      loop:
        - { dst: "nginx.conf", dst_path: "." }
      notify: restart ssl-router

    - name: ssl_router | copy systemd unit file
      ansible.builtin.template:
        src: .service.j2
        dest: "/etc/systemd/system/{{ _ssl_router_systemd_unit_name }}"
        owner: root
        group: root
        mode: "0600"
      notify: restart ssl-router

    # to avoid 2 restarts during the first deploy
    - name: ssl_router | flush handlers
      ansible.builtin.meta: flush_handlers

    - name: ssl_router | start service
      ansible.builtin.systemd:
        name: "{{ _ssl_router_systemd_unit_name }}"
        state: started
        enabled: true
        daemon_reload: true
      ignore_errors: "{{ ansible_check_mode }}"
